add ilovbee B87 keyboard
WestberryTech/qmk_firmware pull request #60
Opened 2024-09-23 08:52 UTC by yangzheng20003

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2024-09-25 03:24 UTC, itarze requested changes
rgblight.c formats only your changes.

2024-09-25 03:24 UTC, itarze commented on keyboards/rk/b87/config.h
> +#define WS2812_SPI_DRIVER       SPIDM2
```suggestion
#define LED_TYPE                RGB

/* WS2812 */
#define WS2812_SPI_DRIVER       SPIDM2
```

2024-09-25 03:24 UTC, itarze commented on keyboards/rk/b87/config.h
> +#define RGBLIGHT_DISABLE_KEYCODES
Move to keyboard.json

2024-09-25 03:24 UTC, itarze commented on keyboards/rk/b87/config.h
> +#define RGBLIGHT_DEFAULT_VAL 60
Move to keyboard.json

2024-09-25 03:24 UTC, itarze commented on keyboards/rk/b87/rgb_record/rgb_record.c
> +    if (status) rgb_hsv_index = (rgb_hsv_index + 1) % temp;
```suggestion
    }
    
    if (status) rgb_hsv_index = (rgb_hsv_index + 1) % temp;
```

2024-09-25 03:24 UTC, itarze commented on keyboards/rk/b87/rgb_record/rgb_record.mk
> +SRC += rgb_record/rgb_rgblight.c
```suggestion
SRC += rgb_record/rgb_rgblight.c

```

2024-12-28 02:30 UTC, closed without merging

2025-05-17 20:19 UTC, Kessmex commented
Would appreciate any follow up on this! Been trying to make this keyboard work for weeks now however I have no coding knowledge and I can't make much by myself